version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees:
      - "Developers"
    reviewers:
      - "Developers"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    open-pull-requests=limit: 10
  package-ecosystem: "docker"
    directory: "/"
    assignees:
      - "Developers"
    reviewers:
      - "Developers"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    open-pull-requests=limit: 2
  package-ecosystem: "github-actions"
    directory: "/"
    assignees:
      - "Developers"
    reviewers:
      - "Developers"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "weekly"
