version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - "3001:3000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    networks:
      - lunar-pay-api
    volumes:
      - ./src:/src
      - ./config:/config
      - ./nest-cli.json:/nest-cli.json

  mongo:
    image: mongo
    ports:
      - '27017-27019:27017-27019'
    restart: always
    env_file:
      - .env
    networks:
      - lunar-pay-api
    volumes:
      - mongo:/data/db

  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - lunar-pay-api

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    env_file:
      - .env
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - lunar-pay-api
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

volumes:
  pg:
    driver: local
    name: lunar-pay-api-pg-db-volume
  mongo:
    name: lunar-pay-api-db-volume

networks:
  lunar-pay-api:
