FROM node:18-alpine AS builder

RUN apk --no-cache add --virtual .builds-deps build-base python3

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install app dependencies
RUN npm ci

COPY . .

FROM node:18-alpine

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/tsconfig*.json ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000
CMD [ "npm", "run", "start:devnet" ]
