app = "lunar-pay-devnet-api"
primary_region = 'lhr'

[env]

[build.args]
  BUILD_ENV="devnet"

[processes]
  api = "node dist/src/main"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['api']