app = "lunar-pay-api"
primary_region = "ams"

[env]
  MONGO_DB_NAME = "lunar-pay"

[build.args]
  BUILD_ENV="testnet"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
