app = "lunar-pay-devnet-api"
primary_region = "lhr"

[build.args]
  BUILD_ENV="devnet"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
