export enum EventIdentifier {
  EGLD_DEPOSIT = 'depositEgld',
  ESDT_DEPOSIT = 'depositEsdt',
  EGLD_WITHDRAWAL = 'withdrawEgld',
  ESDT_WITHDRAWAL = 'withdrawEsdt',
  TOKEN_TRANSFER = 'transferTokens',
  CREATE_PAYMENT_AGREEMENT = 'createPaymentAgreement',
  SIGN_PAYMENT_AGREEMENT = 'signAgreement',
  TRIGGER_AGREEMENT = 'triggerAgreement',
  SUCCESSFUL_AGREEMENT_CHARGES = 'successfulAgreementCharges',
  FAILED_AGREEMENT_CHARGES = 'failedAgreementCharges',
  CREATE_SUBSCRIPTION = 'createSubscription',
  SIGN_SUBSCRIPTION = 'signSubscription',
  TRIGGER_SUBSCRIPTION = 'triggerSubscription',
  SUCCESSFUL_SUBSCRIPTION_CHARGES = 'successfulSubscriptionCharges',
  FAILED_SUBSCRIPTION_CHARGES = 'failedSubscriptionCharges',
}
