app:
  port: 3000

urls:
  blockchainApi: 'https://api.multiversx.com'
  elasticHost: 'https://index.multiversx.com'
  gatewayHost: 'https://gateway.multiversx.com'

contracts:
  lunarPayVault:

nativeAuth:
  maxExpirySeconds: 86400
  acceptedOrigins:
    - lunarpay.finance