app:
  port: 3001

urls:
  blockchainApi: 'https://devnet-api.multiversx.com'
  elasticHost: 'https://devnet-index.multiversx.com'
  gatewayHost: 'https://devnet-gateway.multiversx.com'

contracts:
  lunarPayVault: 'erd1qqqqqqqqqqqqqpgqpt9mvmz3hm7p8vzkmrjrm62m5wtafdnrttdqtma5nf'

nativeAuth:
  maxExpirySeconds: 86400
  acceptedOrigins:
    - https://localhost:3001
    - https://localhost:5173
    - https://lunarpay.finance
    - https://devnet.lunarpay.finance
