app:
  port: 3000

urls:
  blockchainApi: 'https://testnet-api.multiversx.com'
  elasticHost: 'https://testnet-index.multiversx.com'
  gatewayHost: 'https://testnet-gateway.multiversx.com'

contracts:
  lunarPayVault:

nativeAuth:
  maxExpirySeconds: 86400
  acceptedOrigins:
    - https://testnet.lunarpay.finance