name: CI/CD pipeline
on:
  push:
    branches:
      - main
  pull_request:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Fly.io config
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build only for pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          flyctl deploy -c fly.devnet.toml --build-only

      - name: Deploy mainnet app to fly.io
        if: ${{ github.event_name == 'push' }}
        run: |
          flyctl deploy -c fly.devnet.toml --remote-only